###

GET http://localhost:5050

###

POST http://localhost:5050
Content-Type: application/json

{
  "value": "test value"
}

###
POST http://localhost:5050
Content-Type: application/json

{
  "value": "error"
}
