name: Release CA-Boilerplate

on:
  repository_dispatch:
  push:
    tags:
    - "CA-v[0-9]+.[0-9]+.[0-9]+*"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NUGET_APIKEY: ${{ secrets.NUGET_APIKEY}}

jobs:

  OCPI-Net:
    name: OCPI-Net
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify commit
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/main

      - name: Set version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/CA-v/}" >> $GITHUB_ENV

      - name: Build
        run: |
          dotnet build CA-Boilerplate.sln --configuration Release /p:Version=${VERSION}
          dotnet pack CA-Boilerplate.sln --configuration Release /p:Version=${VERSION} --no-build --output .

      - name: Push
        run: |
          dotnet nuget push BitzArt.CA.Core.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_APIKEY}
          dotnet nuget push BitzArt.CA.Infrastructure.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_APIKEY}
          dotnet nuget push BitzArt.CA.Infrastructure.AspNetCore.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_APIKEY}
          dotnet nuget push BitzArt.CA.Persistence.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_APIKEY}
          dotnet nuget push BitzArt.CA.Persistence.EntityFrameworkCore.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_APIKEY}
          dotnet nuget push BitzArt.CA.Persistence.EntityFrameworkCore.Relational.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_APIKEY}
          dotnet nuget push BitzArt.CA.Presentation.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_APIKEY}
